version: '3.1'

services:
  stats-server:
    build: stats-server
    container_name: statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EWM_SERVICE_URL=http://ewm-service:8080

  stats-db:
    image: postgres:14-alpine
    container_name: statistic_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ewm-service
    container_name: exploreWithMe_service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS-SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:14-alpine
    container_name: explore_with_me_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres